server:
  port: 10086
spring:
  application:
    name: euceka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false
  server:
    eviction-interval-timer-in-ms: 30000 # 扫描失效服务的间隔时间（缺省为60*1000ms）
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
